Create table USERS(
	USERNAME VARCHAR(200), 
	PASSWORD VARCHAR(200), 
	FIRSTNAME VARCHAR(200), 
	LASTNAME VARCHAR(200), 
	EMAIL VARCHAR(200), 
	ADDRESS VARCHAR(200), 
	PHONE INTEGER, 
	PRIMARY KEY(USERNAME));
